---
dependencies:
  about: ^1.4.0
  auto_size_text: ^3.0.0-nullsafety.0
  cupertino_icons: ^1.0.2
  geolocator: ^7.0.0-nullsafety.5
  data_connection_checker: ^0.3.4
  dots_indicator: ^1.2.0
  firebase_admob: ^0.11.0+1
  firebase_core: '>=0.7.0 <1.0.0-1.0.nullsafety.0'
  flare_flutter: ^2.0.6
  flutter:
    sdk: flutter
  flutter_google_places: ^0.2.6
  flutter_launcher_icons: ^0.8.1
  flutter_slidable: ^0.6.0-nullsafety.0
  flutter_weather_bg: ^2.8.2
  font_awesome_flutter: ^9.0.0-nullsafety
  get: ^3.24.0
  google_fonts: '>=1.1.2 <2.0.0-nullsafety.0'
  modal_progress_hud: ^0.1.3
  pull_to_refresh: ^1.6.3
  rounded_loading_button: ^1.0.18
  shared_preferences: ^2.0.0-nullsafety.1
  sqflite: ^2.0.0-nullsafety.2
  package_info: '>=0.5.0-nullsafety <2.0.0'
  url_launcher: '>=5.7.10 <6.0.0-nullsafety.7'
  weather_icons: ^2.0.2
description: A Weather app
dev_dependencies:
  flutter_test:
    sdk: flutter
environment:
  sdk: '>=2.12.0-133.7.beta <3.0.0'
flutter:
  assets:
    - assets/log.md
    - assets/icon.png
    - assets/logo.png
  uses-material-design: true
flutter_icons:
  android: launcher_icon
  image_path: assets/icon.png
  ios: true
name: wave_weather
version: 1.0.6+8